<br>
<br>
<br>
<br><br>
<br><br><br>

  <form id="loggin" method="post" enctype="multipart/form-data" action="<?php echo $this->basePath(); ?>/"  novalidate >

        <div class="container col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6 col-lg-offset-4 col-lg-4">
            <br />
            <div class="panel panel-default">
              
                <div class="panel-heading" >
                    <center><h1>Login</h1></center>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-user" style="width: auto"></i>
                            </span>
                            <input id="usuario" runat="server" type="text" class="form-control" name="usuario" placeholder="Usuário" required="" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-lock" style="width: auto"></i>
                            </span>
                            <input id="contrasenia" runat="server" type="password" class="form-control" name="contrasenia" placeholder="Senha" required="" />
                        </div>
                    </div>
                    <button id="btnLogin" runat="server" class="btn btn-default" style="width: 100%">
                        ENTRAR<i class="glyphicon glyphicon-log-in"></i>
                    </button>
                </div>
                    
            </div>
        </div>
      </form>