<br>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <center>
            <h2>
                
                Crear Objeto
            </h2>
            </center>
        </div>
    </div>
    
    <br>
<br>    
<hr>    
    
    <div class="row">
        <div class="col-md-12">

           <form id="nuevo_departamento_form" method="post" enctype="multipart/form-data" action="<?php echo $this->basePath(); ?>/objeto/crearobjeto" class="form-horizontal form-label-left" novalidate >
                <fieldset>

                    <!-- Form Name -->
                    <legend>Crear Objeto</legend>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="textinput">Nombre</label>  
                        <div class="col-md-4">
                            <input id="nombre" name="nombre" type="text" placeholder=" Nombre" class="form-control input-md" required="required">
                           
                        </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="textinput">Descripcion</label>  
                        <div class="col-md-4">
                            <input id="descripcion" name="descripcion" type="text" placeholder="Descripcion (Opcional)" class="form-control input-md" >
                        
                        </div>
                    </div>

                    
<br>
                    <!-- Button (Double) -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="button1id"></label>
                        <div class="col-md-8">
                          
                            <button id="send" type="submit" class="btn btn-success">Crear</button>
                            <a href="<?php echo $this->basePath() . '/objeto' ?>" class="btn btn-default"> <span>Cancelar</span></a>
                          
                        </div>
                    </div>

                </fieldset>
            </form>




        </div>
    </div>
</div>