<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center">
               Prestar Objeto
            </h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

             <form id="Prestamo_form" method="post" enctype="multipart/form-data" action="<?php echo $this->basePath(); ?>/prestamopersona" class="form-horizontal form-label-left" novalidate >
                <fieldset>

                    <!-- Form Name -->
                    <legend>Prestar</legend>

                    <!-- Select Basic -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="selectbasic">Persona</label>
                        <div class="col-md-4">
                            <select id="idPersona" name="idPersona" class="form-control">
                                <option> </option>
                            <?php foreach ($this->personas as $pr) : ?>
                            <option value="<?php echo $pr['id'] ?>"> <?php echo $pr['nombre'] ?> <?php echo ' ' ?> <?php echo $pr['segundoNombre'] ?> <?php echo ' ' ?><?php echo $pr['apellido'] ?> <?php echo ' ' ?><?php echo $pr['segundoApellido'] ?> </option>
                            <?php endforeach; ?>     
                            </select>
                            
                        </div>
                    </div>

                    <!-- Select Basic -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="selectbasic">Objeto</label>
                        <div class="col-md-4">
                            <select id="idObjeto" name="idObjeto" class="form-control">
                            <option> </option>
                            <?php foreach ($this->objetos as $ob) : ?>
                            <option value="<?php echo $ob['id'] ?>"> <?php echo $ob['nombre'] ?> </option>
                            <?php endforeach; ?>     
                            </select>
                        </div>
                    </div>

                    <!-- Textarea -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="descripcion">Descripcion</label>
                        <div class="col-md-4">                     
                            <textarea class="form-control" id="descripcion" name="descripcion"> </textarea>
                        </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="cantidad">Cantidad</label>  
                        <div class="col-md-4">
                            <input id="cantidad" name="cantidad" type="number" name="num" min="0" max="500000" class="form-control input-md">
                           
                        </div>
                    </div>

                    <br>
                     <!-- Button (Double) -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="button1id"></label>
                        <div class="col-md-8">
                          
                            <button id="send" type="submit" class="btn btn-success">Prestar</button>
                            <a href="<?php echo $this->basePath() . '/' ?>" class="btn btn-default"> <span>Cancelar</span></a>
                          
                        </div>
                    </div>
                    
                </fieldset>
            </form>




        </div>
    </div>
</div>