<?php echo $this->doctype(); ?>


<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <?php header("Content-Type: text/html;charset=utf-8"); ?>

        <?php echo $this->headTitle($this->title) ?>
        <?php $this->headMeta()->setCharset('utf-8') ?>
        <?php $this->headMeta()->setCharset('charset=UTF-8') ?>
        <?php $this->headMeta()->setCharset('charset=ISO-8859-1') ?>
        <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php $this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1') ?>

        <?php echo $this->headMeta() ?>



        <!--Importar hojas de estilo-->

        <?php //$this->headLink()->prependStylesheet($this->basePath() . '/tema/build/css/custom.min.css') ?>


        <!-- Bootstrap -->
        <link href="<?php echo $this->basePath() ?>/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <!--        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">-->

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- JavaScript -->
        <script src="<?php echo $this->basePath() ?>/js/bootstrap.min.js" type="text/javascript" ></script>
        <script src="<?php echo $this->basePath() ?>/js/jquery-3.2.1.min.js" type="text/javascript" ></script>

      



        <?php echo $this->headLink() ?>

        <!-- CSS -->

        <!-- Javascript -->
        <!-- Scripts para el panel -->

        <?php //$this->headScript()->prependFile($this->basePath() . '/tema/') ?>


        <?php echo $this->headScript() ?>
    <br>
    <?php if (isset($_SESSION['auth'])) : ?>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb">
                    <li>
                        <a href="<?php echo $this->basePath() . '/principal' ?>" class="divider"> <span>Home</span></a>

                    </li>
                    <li>
                        <a href="<?php echo $this->basePath() . '/persona' ?>" class="divider"> <span>Persona</span></a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath() . '/objeto' ?>" class="divider"> <span>Objeto</span></a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath() . '/prestamopersona' ?>" class="divider"> <span>Prestar</span></a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath() . '/devolucionpersona' ?>" class="divider"> <span>Devolver</span></a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath() . '/historial' ?>" class="divider"> <span>Historial</span></a>
                    </li>
                     <li>
                        <a href="<?php echo $this->basePath() . '/' ?>" class="divider"> <span>Salir</span></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>


</head>

<body class="nav-md">





    <!--page content -->
    <?php echo $this->content; ?>
    <!--/ page content -->


<?php else : ?>

    <!--page content -->
    <?php echo $this->content; ?>
    <!--/ page content -->
    
<?php endif; ?>



    <!-- footer content -->
    <footer>
        <div class="pull-right">
            <!--            <h3>Fin pagina prueba</h3>-->
        </div>
        <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!--       <script src="<?php echo $this->basePath() ?>https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" ></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo $this->basePath() ?>/js/bootstrap.min.js" ></script>
<!--    <script src="js/bootstrap.min.js"></script>-->
</body>
</html>



